image:
  file: .gitpod.dockerfile
ports:
  - port: 8001
    onOpen: ignore
  - port: 3306
    onOpen: ignore
tasks:
  - name: Apache
    command: >
      mkdir /tmp/apache;
      touch /tmp/apache/error.log;
      touch /tmp/apache/access.log;
      export APACHE_PID_FILE="/tmp/apache/PID" APACHE_RUN_USER="gitpod" APACHE_RUN_GROUP="gitpod" APACHE_SERVER_NAME="localhost" APACHE_LOG_DIR="/tmp/apache";
      apache2;
      multitail /tmp/apache/error.log -I /tmp/apache/access.log;
  - name: Allerta
    init: >
      cd frontend;
      npm install;
      npm run build;
      cd ../backend;
      composer install;
  #  command: >
  #    cd server/install;
  #    WEBSERVER_URL=$(gp url 8001 | sed -E s/\\/$//);
  #    mysql -e "CREATE DATABASE IF NOT EXISTS allerta";
  #    mysql -e "CREATE USER 'allerta'@'localhost' IDENTIFIED BY 'allerta_pwd';";
  #    mysql -e "GRANT ALL PRIVILEGES ON * . * TO 'allerta'@'localhost';";
  #    mysqladmin reload;
  #    php install.php config -n "allerta" -u "allerta" -a "allerta_pwd" -o "127.0.0.1" -r "DEV_ENV";
  #    php install.php populate -m "admin" -b -d -s "password" -w "owner" -e "mail@mailserver.local" -u "$WEBSERVER_URL/";
  #    touch runInstall.php;
  #    gp await-port 8001; gp preview "$(gp url 8001)";
  #    cd ..;
  #    wget https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.php;
  #    mv adminer-4.8.0.php adminer.php;
  #    clear;
  #    echo "$(tput setaf 2)Full webserver url$(tput sgr0) $(tput setaf 4)$WEBSERVER_URL$(tput sgr0)";
  #    echo "$(tput setaf 2)Allerta username$(tput sgr0) $(tput setaf 4)admin$(tput sgr0)";
  #    echo "$(tput setaf 2)Allerta password$(tput sgr0) $(tput setaf 4)password$(tput sgr0)";
  #    echo "$(tput setaf 2)PHP Adminer$(tput sgr0) $(tput setaf 4)$WEBSERVER_URL/adminer.php$(tput sgr0)";
  #    echo "$(tput setaf 2)DB user$(tput sgr0) $(tput setaf 4)allerta$(tput sgr0)";
  #    echo "$(tput setaf 2)DB password$(tput sgr0) $(tput setaf 4)allerta_pwd$(tput sgr0)";
  #    echo "$(tput setaf 2)DB name$(tput sgr0) $(tput setaf 4)allerta$(tput sgr0)";
  #    printf "\n";
  #    echo "Good luck. Happy coding and testing!"
vscode:
  extensions:
    - gruntfuggly.todo-tree@0.0.205:sbsZJOTJzKZtMVHQuS2iPw==
    - shelex.vscode-cy-helper@1.1.0:U9ok2y1bSmqn17OMuRMOfw==
