version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mariadb:11.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306
    volumes:
      - mariadb-data:/var/lib/mysql
volumes:
  mariadb-data:
